# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/*
- main/*

pool:
  vmImage: ubuntu-latest

variables:
   BuildConfiguration: dotnet build
   DotNetVersion: '3.1.x'  # Specify the desired .NET Core SDK version here

steps:
- task: UseDotNet@2
  inputs:
    version: '$(DotNetVersion)'  # Use the specified .NET Core SDK version

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    restoreArguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

 