# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/*
- main/*

pool:
  vmImage: ubuntu-latest

variables:
   Build configuration: dotnet build
   dotnetVersion: '2.0'
  


steps:
 - task: DotNetCoreCLI@2
   inputs:
     majorVersion: $(dotnetVersion)
     command: 'build'
     projects: '**/*.csproj'
     arguments: '--configuration$(Build configuration)'
    
 